### ISSUE TITLE
Suggested improvement to ease maintenance

### ISSUE THREAD

**Issue by leggetter** [darkwhispering/pusher-for-codeigniter#2]
Right now the API requires all the PHP `Pusher` functions to be duplicated on the `Ci_pusher` class. If any changes take place on the `Pusher` API then those need to also be added to the `Ci_pusher` class.

Of course, no breaking changes should happen between major versions of the official PHP library. But any major version changes will require additional work to update `Ci_pusher`.

If `Ci_pusher` instead had a simple `getPusher()` function that returned the actual `Pusher` instance from the official library maintenance becomes much easier - almost non-existent.

So, usage would require one additional function call. But it may be worth considering. Usage would instead be:

```php
$pusher = $this->ci_pusher->getPusher();
$pusher->trigger(...);
$pusher->socket_auth(...);
```

Where all the functions are executed on the real `Pusher` instance and not the CI proxy object.

**Comment by darkwhispering** [comment]
Agreed on maintenance and you idea is great.
